spring:
  application:
    name: article-mongo
  profiles:
    active: dev
  cloud:
    config:
      uri: http://configserver:8071

logging:
  level:
    org.springframework.web: WARN
    com.example: DEBUG
