spring:
  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
      kafka-service:
        binder:
          zkNodes: kafka-service
          brokers: kafka-service
          defaultBrokerPort: 9092

