spring:
  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
      kafka:
        binder:
          zkNodes: zookeeper-cluster:2181
          brokers: kafka-service
          defaultBrokerPort: 9092

