apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
type: Opaque
data:
  ME_CONFIG_MONGODB_ADMINUSERNAME: cm9vdA==
  ME_CONFIG_MONGODB_ADMINPASSWORD: cm9vdA==
  ME_CONFIG_MONGODB_SERVER: bW9uZ28=
  ME_CONFIG_MONGODB_PORT: MjcwMTc=
