apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv-volume
  labels:
    type: local
    app: pgadmin
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pgdata"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pv-claim
  labels:
    app: pgadmin
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi







