name: Article_application

on:
  push: 
    branches: [ main ]
    
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push config
      uses: docker/build-push-action@v3
      with: 
        context: config
        file: config/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/test_repository:tagname
    -
      name: Build and push article-mongo
      uses: docker/build-push-action@v3
      with: 
        context: article-mongo
        file: article-mongo/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/test_repository:tagname
    -
      name: Build and push article-postgres
      uses: docker/build-push-action@v3
      with: 
        context: article-postgres
        file: article-postgres/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/test_repository:tagname
      
    
